import Head from 'next/head'
import Image from 'next/image'
import LoadWASM from '../components/LoadWASM'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <LoadWASM src="/main.wasm">
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://kaenova.my.id">Next.js + Golang WASM</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>src/pages/index.js</code> and <code className={styles.code}>src/go/main.go</code>
          </p>

          <div>

            {/* This is how you call WASM function */}
            <button onClick={() => window.change()} id="changeme" className={styles.card}>
              Click Me!
            </button>

          </div>


        </main>
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
          <a
            href="https://github.com/kaenova"
          >
            Template by KMA
          </a>
        </footer>
      </div>
    </LoadWASM>
  )
}
